peakasthma-web/config/routes.rb
Rails.application.routes.draw do

  get 'twilio_messages/reply'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  mount Avocado::Engine => '/avocado'

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
                     :controllers => {:confirmations => 'confirmations'}
  devise_scope :user do
    put "/confirm" => "confirmations#confirm"
  end

  namespace :api, defaults: { format: :json } do
    devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' }

    get 'users/current', to: 'users#current'
    post 'users/accept_policy', to: 'users#accept_policy'
    get 'tip', to: 'tips#get_tip'
    post 'weather', to: 'tips#get_weather'
    post 'video', to: 'videos#likeVideo'
    get 'video', to: 'videos#avbVideo'
    get 'medicationreminder/:minutes/:color', to: 'taken_prescription_records#reminder_later'
    get 'incentive', to: 'incentive#incentive'
    get 'survey', to: 'survey#survey'
    post 'clincard_balance_request', to: 'clincard_balance_requests#send_request'
    resources :activities, only: [:index]
    resources :peak_flows, only: [:create, :index]
    resources :prescriptions, only: [:index] do
      post :notifications, on: :collection
      post :reports, on: :collection
      post :remindmelater, on: :collection
    end
    resources :symptoms, only: [:index]
    resources :read_notification_records, only: [:create]
    resources :taken_prescription_records, only: [:create]
    resources :notifications, only: [:index]

    namespace :control, defaults: { format: :json } do
      get 'users/current', to: 'users#current'
      post 'users/accept_policy', to: 'users#accept_policy'
      resources :activities, only: [:index]
      resources :diet_records, only: [:create, :index, :update]
      resources :notifications, only: [:index]
      post 'daily_reminder', to: 'notifications#daily_reminder'
      resources :read_notification_records, only: [:create]
      get 'incentive', to: 'incentive#incentive'
      get 'control_survey', to: 'control_survey#survey'
      post 'clincard_balance_request', to: 'clincard_balance_requests#send_request'
    end
  end
  
  resources :users do
    post :create_admin, on: :collection
  end

  resource :twilio_notifications do
    collection do
      post 'reply'
    end
  end
  post 'red_voice', to: 'twilio_notifications#red_voice', defaults: { format: 'xml' }
  post 'yellow_voice', to: 'twilio_notifications#yellow_voice', defaults: { format: 'xml' }
  get 'tip/:id', to: 'tips#send_tip'
  resources :medications
  resources :symptoms
  resources :tips
  resources :videos
  resources :exacerbations
  resources :patient_reward_records
  resources :control_patient_reward_records
  resources :patient_visits_records
  resources :control_patient_visits_records
  resources :clincard_balance_requests
  resources :alert_tables
  resources :patients, only: [:index, :show, :edit, :update, :new, :create] do
    resources :peak_flows, only: [:index]
    resources :prescriptions do
      get :fields, on: :collection
      resources :prescription_refill_records
    end
    resources :prescriptions
    resources :notifications do
      get :fields, on: :collection
    end
    resources :guardians
    resources :reports, only: [:show]
  end
  resources :notifications, only: [:index, :create, :edit, :update, :new, :destroy] do
    get :fields, on: :collection
  end

  resources :control_patients, only: [:index, :show, :edit, :update, :new, :create] do
    resources :control_notifications
  end
  resources :control_notifications, only: [:index, :create, :edit, :update, :new, :destroy]
  root to: 'dashboard#root'
end

peakasthma-web/app/models/patient.rb
class Patient < ApplicationRecord
  after_initialize :set_default_zone_minimums

  belongs_to :user
  has_many :guardians
  has_many :prescriptions
  has_many :symptom_reports
  has_many :peak_flows
  has_many :activities
  has_many :read_notification_records
  has_many :taken_prescription_records
  has_many :prescription_refill_records
  has_many :clincard_balance_requests
  has_and_belongs_to_many :videos
  has_and_belongs_to_many :notifications

  accepts_nested_attributes_for :user

  scope :created_before, -> (date) { where("created_at < ?", date) }

  validates :birthday, presence: true
  validate :validate_age
  validates :gender, presence: true
  validates :height, inclusion: { in: 0..90, message: 'The height must be between 0 and 90' }
  validates :yellow_zone_minimum, inclusion: { in: 60..800, message: 'The yellow zone minimum peakflow value should be between 60 and 800' }
  validates :yellow_zone_maximum, inclusion: { in: 60..800, message: 'The yellow zone maximum peakflow value should be between 60 and 800' }
  validate :validate_zone_value 
  validates :phone, format: { with: /\A^[1-9]\d{2}-\d{3}-\d{4}\z/, message: "Please enter phone number in correct format: 123-456-7890"}, presence: true
  validates :redcap_id, presence: true, uniqueness: true

  GENDERS = [:male, :female, :other].freeze
  enum gender: GENDERS

  DEFAULT_YELLOW_ZONE_MINIMUM = 170
  DEFAULT_YELLOW_ZONE_MAXIMUM = 220

  delegate :first_name, :last_name, :email, :username, :full_name, :disabled, to: :user

  def validate_age
    if birthday.present? && birthday > 12.years.ago.to_date
      errors.add(:birthday, 'The patient should be over 12 years old.')
    elsif birthday.present? && birthday < 21.years.ago.to_date
      errors.add(:birthday, 'The patient should be less than 21 years old.')
    end
  end

  def validate_zone_value
    if yellow_zone_maximum.present? && yellow_zone_minimum.present? && yellow_zone_maximum <= yellow_zone_minimum
      errors.add(:yellow_zone_maximum, 'The yellow zone maximum peakflow value should be larger than the yellow zone minimum peakflow value')
    end
  end

  def self.in_zone(zone)
    Patient.select { |patient| patient.level == zone }
  end

  def self.app_usage_percentage
    return 0.0 if count == 0

    total_patients = count
    recently_updated_patients = select { |patient| patient.peak_flows.older_than(1.days).any? }.count
    100 * (recently_updated_patients.to_f / total_patients.to_f)
  end

  def level
    peak_flows&.last&.level
  end

  def zone_percentage(target_level)
    return 0 unless peak_flows.any?

    total_time = Time.current - peak_flows.order(created_at: :asc).first.created_at
    target_zone_time = time_in_level(target_level)

    total_time > 0 ? (100 * target_zone_time / total_time).round : 0
  end

  def height_in_feet
    return I18n.t('common.values.n_a') unless height
    feet = height / 12
    inches = height % 12
    "#{feet}\' #{inches}\""
  end

  def weight_in_pounds
    return I18n.t('common.values.n_a') unless weight
    "#{weight.round(2)} lbs"
  end

  def green_zone_range
    I18n.t('patient.views.labels.green_zone_range', max_flow: yellow_zone_maximum, min_flow: yellow_zone_minimum)
  end

  def yellow_zone_range
    I18n.t('patient.views.labels.yellow_zone_range', max_flow: yellow_zone_maximum, min_flow: yellow_zone_minimum)
  end

  def red_zone_range
    I18n.t('patient.views.labels.red_zone_range', max_flow: yellow_zone_maximum, min_flow: yellow_zone_minimum)
  end

  def read_notifications
    read_notification_records.map(&:notification)
  end

  def unread_notifications
    notifications.where.not(id: read_notifications.pluck(:id))
  end

  def recommended_prescription_for_level(level)
    if level == :red_now
      level = :red
    end
    for prescription in prescriptions
      for prescription_level in prescription.prescription_levels
        if(LevelType.find(prescription_level.level_id).kind.downcase.to_s == level.to_s)
          return prescription 
        end
      end
    end
    return nil
  end

  def reports
    reports = []
    report_count = 0
    enroll_date = Date.parse(created_at.to_s)

    until (enroll_date + (report_count + 1) * 30) > Date.today() do
      report = {
        start: enroll_date + report_count * 30,
        end: (enroll_date + (report_count + 1) * 30) - 1,
        report_id: report_count + 1
      }
      reports << report

      report_count += 1
    end

    return reports.reverse
  end

  private
    def set_default_zone_minimums
      self.yellow_zone_minimum ||= DEFAULT_YELLOW_ZONE_MINIMUM
      self.yellow_zone_maximum ||= DEFAULT_YELLOW_ZONE_MAXIMUM
    end

    def time_in_level(target_level)
      target_zone_time = 0
      sorted_peak_flows = peak_flows.order(created_at: :asc)

      sorted_peak_flows.each_with_index do |peak_flow, index|
        time_to_next_entry = sorted_peak_flows[index + 1]&.created_at || Time.current
        target_zone_time += time_to_next_entry - peak_flow.created_at if peak_flow.level == target_level
      end

      target_zone_time
    end
end

peakasthma-web/app/controllers/patients_controller.rb
require 'will_paginate/array'
class PatientsController < ApplicationController
  authenticated!
  before_action :redirect_wrong_patient
  before_action :find_patient, only: [:show, :edit, :update]

  def index
    if params[:search].blank?
      @patients = Patient.all.order(updated_at: :desc).paginate(page: params[:page])
    else
      @parameter = params[:search].downcase
      @patients = Patient.joins(:user).all.where("lower(CONCAT(users.first_name, ' ', users.last_name)) LIKE :search", search: "%#{@parameter}%").order(updated_at: :desc).paginate(page: params[:page])
    end

  end

  def update
    @patient.update(patient_params)
    respond_with @patient
  end

  def show
    # @exacerbations = Exacerbation.where("patient_id = ?", @patient.id).order(created_at: :desc).paginate(page: params[:exacerbations_page], per_page: 6)
    @exacerbations = Exacerbation.where('patient_id = ?', @patient.id)
                                 .select('"exacerbations".*, "ahoy_messages".opened_at')
                                 .joins('LEFT JOIN ahoy_messages ON exacerbations.id = ahoy_messages.exacerbation_id AND ahoy_messages.user_id != 1 and ahoy_messages.user_id IS NOT NULL')
                                 .order(created_at: :desc)
                                 .paginate(page: params[:exacerbations_page], per_page: 6)
    @exacerbations.inspect
    @refill_record = PrescriptionRefillRecord.where("patient_id = ?", @patient.id).order(created_at: :desc).paginate(page: params[:refill_page], per_page: 12)
    @incentives
    @month_incentives = 0
    @total_incentives = []
    @all_incentives = []
    @days = days_after_enroll()
    @months = @days / 30 + 1
    @monthly_rewards_days = Hash.new
    for i in (1..@months)
      @monthly_rewards_days[i] = 0
    end

    @all_incentives = IncentiveRecord.where(patient_id: params[:id]).order(month: :asc, week: :asc, day: :asc)
    @all_incentives = @all_incentives.to_a
    @all_incentives.each_with_index do |incentive, index|
      total_days = (incentive.week - 1) * 7 + incentive.day
      true_month = (total_days - 1) / 30 + 1
      if @monthly_rewards_days.include?(true_month) and @monthly_rewards_days[true_month] >= 20
        @all_incentives[index].get_incentive = false
      else
        @all_incentives[index].get_incentive = true
        @monthly_rewards_days[true_month] += 1
      end 
      @all_incentives[index]['month'] = true_month
      @all_incentives[index]['day'] = total_days - 30 * (true_month-1)
    end
    @incentives =  @all_incentives.paginate(page: params[:incentives_page], per_page: 5)
    @len = @monthly_rewards_days.length - 1
    if @len >= 0
      @month_incentives = @monthly_rewards_days.values[@len]
      last_month = @monthly_rewards_days.keys[@len]
      @monthly_rewards_days.delete(last_month)
    else
      @month_incentives = 0
      last_month = 0
    end
    @total_incentives = @all_incentives.select do |elem|
      elem.get_incentive == true
    end

    @prescription_history = Prescription.where("patient_id = ?", @patient.id).order(id: :desc).paginate(page: params[:page])

    twilio_phone_call_status
  end

  def edit
    fill_redcap_data(@patient, params['import-redcap-id'])
  end

  def new
    @patient = Patient.new
    @patient.user = User.new
    fill_redcap_data(@patient, params['import-redcap-id'])
  end

  def create
    @patient = Patient.create(patient_params)
    respond_with @patient
  end

  private
    def patient_params
      valid_params = params.require(:patient).permit(
        :yellow_zone_maximum,
        :yellow_zone_minimum,
        :medication_reminders,
        :medication_reminder_time,
        :report_reminder_time,
        :gender,
        :birthday,
        :height,
        :weight,
        :phone, 
        :physician,
        :remind_later_time,
        :time,
        :redcap_id,
        user_attributes: [:id, :first_name, :last_name, :username, :email, :role, :disabled])
  
        if valid_params[:medication_reminder_time]
          valid_params[:medication_reminder_time] = valid_params[:medication_reminder_time].to_time
        end

        if valid_params[:report_reminder_time]
          valid_params[:report_reminder_time] = valid_params[:report_reminder_time].to_time
        end

        valid_params[:user_attributes][:encrypted_password] = '$2a$11$cixW0odcieVc4XgCQ.mu.evLbsvuR/6aqANX/8Sup8EXPU/gkDNP6' if action_name == 'create'

        valid_params
    end

    def find_patient
      @patient = Patient.find(params[:id])
      @patient
    end

    def days_after_enroll()
      @enroll_date = @patient.created_at.to_date
      @current_date = Time.now.utc.to_date
      @days = @current_date - @enroll_date
      @days = @days.to_i
    end

    def day
        @days = days_after_enroll()
        @week_day = (@days % 7) + 1
    end

    def week
        @days = days_after_enroll()
        @week = (@days / 7) + 1
    end

    def month
        @month = ((week - 1) / 4) + 1 
    end

    def fill_redcap_data(patient, redcap_id)
      info = RedcapAPI.get_patient_demographic_info(redcap_id)

      patient.birthday = info[:dob] if info[:dob] != nil
      patient.gender = info[:gender] if info[:gender] != nil
      patient.physician = info[:pcp] if info[:pcp] != nil
      patient.height = info[:height] if info[:height] != nil
      patient.weight = info[:weight] if info[:weight] != nil
      patient.redcap_id = redcap_id if redcap_id != nil

      patient.user.first_name = info[:first_name] if info[:first_name] != nil
      patient.user.last_name = info[:last_name] if info[:last_name] != nil
    end

    def twilio_phone_call_status
      account_sid = Rails.application.secrets.twilio_sid
      auth_token = Rails.application.secrets.twilio_token
      @client = Twilio::REST::Client.new account_sid, auth_token
      calls = @client.calls.list()
      @exacerbation_phone_call_status_dict = Hash.new
      @exacerbation_phone_calls = TwilioPhoneCall.all
      
      for exacerbation_phone_call in @exacerbation_phone_calls
        
        call = calls.select { |call| call.sid == exacerbation_phone_call.twilio_sid }
        if call[0].present?
            @exacerbation_phone_call_status_dict[exacerbation_phone_call.exacerbation_id] = call[0].status
        end
      end
    end
end

peakasthma-web/app/views/patients/_form.html.erb
<div class="row">
  <div class="col-xs-12">
    <% if controller.action_name == "new" || controller.action_name == "create" %>
      <%= form_tag(new_patient_url, method: "get") do %>
        <%= label_tag("import-redcap-id", "REDCap ID:") %>
        <%= text_field_tag("import-redcap-id") %>
        <%= submit_tag("Import Demographic Information from REDCap", class: "btn btn-info back-btn") %>
      <% end %>
    <% elsif controller.action_name == "edit" || controller.action_name == "update" %>
      <%= form_tag(edit_patient_url(params[:id]), method: "get") do %>
        <%= label_tag("import-redcap-id", "REDCap ID:") %>
        <%= text_field_tag("import-redcap-id") %>
        <%= submit_tag("Import Demographic Information from REDCap", class: "btn btn-info back-btn") %>
      <% end %>
    <% end %>
  </div>
</div>
<%= simple_form_for @patient do |patient| %>
  <% patient.simple_fields_for :user do |user| %>
    <%= user.input :id, as: :hidden %>
    <div class="row">
      <div class="col-xs-12">
        <div class="panel panel-default">
          <div class="panel-body">
            <h2>
              <%= t('patient.views.headers.personal_information') %>
            </h2>
              <div class="row">
                <div class="col-xs-6">
                  <%= user.input :first_name %>
                </div>
                <div class="col-xs-6">
                  <%= user.input :last_name %>
                </div>
              </div>
            <div class="row">
              <div class="col-xs-4 col-md-3">
                <%= patient.input :gender, collection: Patient::GENDERS %>
              </div>
              <div class="col-xs-8 col-md-3">
                <%= patient.input :birthday, html5: true%>
              </div>
              <div class="col-xs-6 col-md-3">
                <%= patient.input :weight %>
              </div>
              <div class="col-xs-6 col-md-3">
                <%= patient.input :height,  input_html: { min: '0', max: '90', value: patient.object.height || '0' } %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <div class="panel panel-default">
          <div class="panel-body">
            <h2>
              <%= t('patient.views.headers.additional_info') %>
            </h2>
            <div class="row">
              <div class="col-xs-12 col-md-8">
                <%= user.input :username %>
                <%= user.input :email %>
                <%= user.input :role, as: :hidden, html5: true, input_html: { value: :patient } %>
              </div>
              <div class="col-xs-12 col-md-4">
                <%= patient.input :phone, placeholder: "123-456-7890" %>
                <%= patient.input :physician %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-4">
        <div class="panel panel-default">
          <div class="panel-body">
            <h2>
              <%= t('patient.views.headers.asthma_zone_params') %>
            </h2>
            <div class="row">
              <div class="col-xs-6">
                <%= patient.input :yellow_zone_minimum %>
              </div>
              <div class="col-xs-6">
                <%= patient.input :yellow_zone_maximum %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-md-4">
        <div class="panel panel-default">
          <div class="panel-body">
            <h2>
              <%= t('patient.views.headers.redcap_id') %>
            </h2>
            <%= patient.input :redcap_id, label: 'Record ID' %>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-md-4">
        <div class="panel panel-default">
          <div class="panel-body">
            <h2>
              <%= t('user.views.headers.account_status') %>
            </h2>
            <%= user.input :disabled, as: :select, label: 'Mobile App Usage', collection: [['Active', false], ['Disabled', true]], include_blank: false %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-6">
        <div class="panel panel-default">
          <div class="panel-body">
            <h2>
              <%= t('patient.views.headers.medication_reminders') %>
            </h2>
            <%= patient.input :medication_reminders, as: :hidden, wrapper: :checkbox, :input_html => { :value => 1 } %>
            <%= patient.input :remind_later_time, as: :hidden, :input_html => { :value => 0 } %>
            <%= patient.input :medication_reminder_time, as: :hidden, html5: true %>
            <%= patient.simple_fields_for :time do |nf| %>
              <%= nf.input :medication_reminder_time, as: :time, html5: true %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-md-6">
        <div class="panel panel-default">
          <div class="panel-body">
            <h2>
              <%= t('patient.views.headers.report_reminders') %>
            </h2>
            <%= patient.input :report_reminder_time, as: :hidden, html5: true %>
            <%= patient.simple_fields_for :time do |nf| %>
              <%= nf.input :report_reminder_time, as: :time, html5: true %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <%= patient.button :submit, class: 'btn-default' %>
      </div>
    </div>
    </div>
    </div>
  <% end %>
<% end %>

peakasthma-web/app/views/patients/_medication_tables.html.erb
<div class="patient-profile__table-header">
    PRESCRIPTION INFO
</div>
<% @patient.prescriptions.each_with_index do |prescription, index| %>
  <% if prescription.valid_status %>
    <div class="panel panel-default">
        <div class="patient-profile-table">
            <div class="patient-profile-table__row">
                <div class="patient-profile-table__header patient-profile-table__header--highlighted">
                    <%= "#{t('prescription.label')} \##{(prescription.id)}" %>
                </div>
                <% if current_user&.admin? %>
                <div class="patient-profile-table__cell">
                    
                        <% if prescription.confirm_status %>
                          <button class="btn btn-success btn-xs" disabled>Confirmed</button>
                        <% else %>
                        <%= link_to patient_prescription_path(@patient, prescription, :prescription => {:confirm_status => true, :confirm_at => Time.now.getutc}),
                              method: :patch, remote: true, id: "#{prescription.id}_read" do %>
                            <button class="btn btn-warning btn-xs">Confirm</button>
                          <% end %>
                        <% end %>
                    
                    <%= link_to edit_patient_prescription_path(@patient, prescription), method: :get, class: 'patient-profile-table__action', id: "edit-prescription-#{prescription.id}" do %>
                    <span class="glyphicon glyphicon-edit text-info"></span>
                    <% end %>
                    <%= link_to patient_prescription_path(@patient, prescription), method: :delete, data: {confirm: t('prescription.views.delete_confirm')}, class: 'patient-profile-table__action', id: "delete-prescription-#{prescription.id}" do %>
                    <span class="glyphicon glyphicon-remove text-danger"></span>
                    <% end %>
                </div>
                <% end %>
            </div>
            <%= render 'shared/mobile_table_row', block_name: 'patient-profile-table', header: t('medication.model.name'), value: prescription.medication.name %>
            <%= render 'shared/mobile_table_row', block_name: 'patient-profile-table', header: t('prescription.model.level'), value: prescription.level_names %>
            <%= render 'shared/mobile_table_row', block_name: 'patient-profile-table', header: t('medication.model.formulation'), value: prescription.formulation.kind %>
            <%= render 'shared/mobile_table_row', block_name: 'patient-profile-table', header: t('medication.model.dosage'), value: prescription.dosage %>
            <%= render 'shared/mobile_table_row', block_name: 'patient-profile-table', header: t('medication.model.frequency'), value: prescription.frequency.kind %>
            <%= render 'shared/mobile_table_row', block_name: 'patient-profile-table', header: t('prescription.model.reminder_day'), value: t("Every Month ( #{ prescription.reminder_day } )") %>
            <!-- <% if current_user&.admin? %>
            <%= link_to new_patient_prescription_prescription_refill_record_path(@patient, prescription), class: 'btn btn-info btn-block' do %>
              <span class="glyphicon glyphicon-time"></span>
              Report Refill Date
            <% end %>
          <% end %> -->
        </div>
    </div>
  <% end %>
<% end %>

peakasthma-web/app/views/patients/_peak_flow_popover.html.erb
<!-- Must use single quotes here so the JS can render it properly -->
<div class='peak-flow-popover'>
  <ul class='peak-flow-popover__list'>
    <% peak_flow.symptoms.each do |symptom| %>
      <li>
        <%= symptom.name %>
      </li>
    <% end %>
  </ul>
</div>

peakasthma-web/app/views/patients/new.html.erb
<%= render 'form' %>

peakasthma-web/app/views/patients/show.html.erb
<div class="patient-profile">
  <div class="row">
    <div class="col-lg-3 col-md-4">
      <% if current_user&.admin? %>
        <%= link_to new_patient_notification_path(@patient), class: 'btn btn-success btn-block' do %>
          <span class="glyphicon glyphicon-envelope"></span>
          Send Message
        <% end %>
      <% end %>
      <br>
      <% if current_user&.admin? %>
        <%= link_to edit_patient_path(@patient), class: 'btn btn-info btn-block' do %>
          <span class="glyphicon glyphicon-edit"></span>
          <%= t('patient.views.buttons.edit') %>
        <% end %>
      <% end %>
      <br>
      <%= render partial: 'patients/patient_info_table' %>
      <%= render partial: 'patients/patient_additional_info_table' %>
      <% if current_user&.admin? %>
        <%= render partial: 'incentive/rewards_table' %>
      <% end %>
      <%= render partial: 'patients/asthma_zone_parameters' %>
      <%= render partial: 'patients/guardian_tables' %>
      <% if current_user&.admin? %>
        <%= link_to new_patient_guardian_path(@patient), class: 'btn btn-primary btn-block' do %>
          <span class="glyphicon glyphicon-plus"></span>
          <%= t('guardian.views.buttons.create') %>
        <% end %>
      <% end %>
      <br>
      <%= render partial: 'patients/medication_tables' %>
      <% if current_user&.admin? %>
        <%= link_to new_patient_prescription_path(@patient), class: 'btn btn-success btn-block' do %>
          <span class="glyphicon glyphicon-plus"></span>
          <%= t('prescription.views.buttons.create') %>
        <% end %>
      <% end %>
      <br>
    </div>

    <div class="col-lg-9 col-md-8">
      <div class="row">
        <div class="col-xs-4">
          <%= render 'patients/zone_percentage', level: :green %>
        </div>
        <div class="col-xs-4">
          <%= render 'patients/zone_percentage', level: :yellow %>
        </div>
        <div class="col-xs-4">
          <%= render 'patients/zone_percentage', level: :red %>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-12">
          <div class="panel panel-default">
            <div class="recent-peak-flows__header">
              <%= t('dashboard.headers.zone_patients') %>
            </div>
            <%= render 'exacerbations/exacerbation_table', root_page: false %>
          </div>
        </div>
      </div>

      <% if current_user&.admin? %>
        <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-default">
              <div class="recent-peak-flows__header">
                <%= t('dashboard.headers.incentive') %>
              </div>
              <%= render 'incentive/incentives_table' %>
            </div>
          </div>
        </div>
      <% end %>
      
      <% if current_user&.admin? %>
        <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-default">
              <div class="recent-peak-flows__header">
                <%= t('dashboard.headers.monthly_reward') %>
              </div>
              <%= render 'incentive/monthly_reward_table' %>
            </div>
          </div>
        </div>
      <% end %>
      
      <div class="row">
        <div class="col-lg-12">
          <div class="panel panel-default">
            <div class="recent-peak-flows">
              <div class="recent-peak-flows__header">
                <%= t('patient.views.headers.recent_peak_flows') %>
                <%= link_to t('patient.buttons.view_all'), patient_peak_flows_path(@patient), class: 'recent-peak-flows__view-all' %>
              </div>
              <%= render 'patients/peak_flows', peak_flows: @patient.peak_flows.order(created_at: :desc).limit(10) %>
            </div>
          </div>
        </div>
      </div>

      <% if current_user&.admin? %>
        <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-default">
              <div class="recent-peak-flows__header">
                <%= t('patient.views.headers.monthly_report') %>
              </div>
              <%= render 'reports/report_table', reports: @patient.reports() %>
            </div>
          </div>
        </div>
      <% end %>

      <% if current_user&.admin? %>
        <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-default">
              <div class="recent-peak-flows__header">
                <%= t('patient.views.headers.prescription_history') %>
              </div>
              <%= render 'patients/prescriptions_history_table' %>
            </div>
          </div>
        </div>
      <% end %>
        
  </div>

  <div class="row">
    
      <!-- <div class="col-lg-8 col-md-8">
        <div class="panel panel-default">
          <%= render 'prescription_refill_records/prescription_refill_record_table', root_page: false %>
        </div>
      </div> -->

  </div>
</div>