peakasthma-web/config/routes.rb
Rails.application.routes.draw do

  get 'twilio_messages/reply'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  mount Avocado::Engine => '/avocado'

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
                     :controllers => {:confirmations => 'confirmations'}
  devise_scope :user do
    put "/confirm" => "confirmations#confirm"
  end

  namespace :api, defaults: { format: :json } do
    devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' }

    get 'users/current', to: 'users#current'
    post 'users/accept_policy', to: 'users#accept_policy'
    get 'tip', to: 'tips#get_tip'
    post 'weather', to: 'tips#get_weather'
    post 'video', to: 'videos#likeVideo'
    get 'video', to: 'videos#avbVideo'
    get 'medicationreminder/:minutes/:color', to: 'taken_prescription_records#reminder_later'
    get 'incentive', to: 'incentive#incentive'
    get 'survey', to: 'survey#survey'
    post 'clincard_balance_request', to: 'clincard_balance_requests#send_request'
    resources :activities, only: [:index]
    resources :peak_flows, only: [:create, :index]
    resources :prescriptions, only: [:index] do
      post :notifications, on: :collection
      post :reports, on: :collection
      post :remindmelater, on: :collection
    end
    resources :symptoms, only: [:index]
    resources :read_notification_records, only: [:create]
    resources :taken_prescription_records, only: [:create]
    resources :notifications, only: [:index]

    namespace :control, defaults: { format: :json } do
      get 'users/current', to: 'users#current'
      post 'users/accept_policy', to: 'users#accept_policy'
      resources :activities, only: [:index]
      resources :diet_records, only: [:create, :index, :update]
      resources :notifications, only: [:index]
      post 'daily_reminder', to: 'notifications#daily_reminder'
      resources :read_notification_records, only: [:create]
      get 'incentive', to: 'incentive#incentive'
      get 'control_survey', to: 'control_survey#survey'
      post 'clincard_balance_request', to: 'clincard_balance_requests#send_request'
    end
  end
  
  resources :users do
    post :create_admin, on: :collection
  end

  resource :twilio_notifications do
    collection do
      post 'reply'
    end
  end
  post 'red_voice', to: 'twilio_notifications#red_voice', defaults: { format: 'xml' }
  post 'yellow_voice', to: 'twilio_notifications#yellow_voice', defaults: { format: 'xml' }
  get 'tip/:id', to: 'tips#send_tip'
  resources :medications
  resources :symptoms
  resources :tips
  resources :videos
  resources :exacerbations
  resources :patient_reward_records
  resources :control_patient_reward_records
  resources :patient_visits_records
  resources :control_patient_visits_records
  resources :clincard_balance_requests
  resources :alert_tables
  resources :patients, only: [:index, :show, :edit, :update, :new, :create] do
    resources :peak_flows, only: [:index]
    resources :prescriptions do
      get :fields, on: :collection
      resources :prescription_refill_records
    end
    resources :prescriptions
    resources :notifications do
      get :fields, on: :collection
    end
    resources :guardians
    resources :reports, only: [:show]
  end
  resources :notifications, only: [:index, :create, :edit, :update, :new, :destroy] do
    get :fields, on: :collection
  end

  resources :control_patients, only: [:index, :show, :edit, :update, :new, :create] do
    resources :control_notifications
  end
  resources :control_notifications, only: [:index, :create, :edit, :update, :new, :destroy]
  root to: 'dashboard#root'
end

peakasthma-web/app/models/control_patient.rb
class ControlPatient < ApplicationRecord
  belongs_to :user
  has_many :control_activities
  has_many :diet_records
  has_many :read_control_notification_records
  has_and_belongs_to_many :control_notifications, join_table: :control_notifications_control_patients

  accepts_nested_attributes_for :user

  scope :created_before, -> (date) { where("created_at < ?", date) }

  validates :birthday, presence: true
  validate  :validate_age
  validates :gender, presence: true
  validates :height, inclusion: { in: 0..90, message: 'The height must be between 0 and 90' }
  validates :phone, format: { with: /\A^[1-9]\d{2}-\d{3}-\d{4}\z/, message: "Please enter phone number in correct format: 123-456-7890"}, presence: true
  validates :redcap_id, presence: true, uniqueness: true

  GENDERS = [:male, :female, :other].freeze
  enum gender: GENDERS

  delegate :first_name, :last_name, :email, :username, :full_name, :disabled, to: :user

  def validate_age
    if birthday.present? && birthday > 12.years.ago.to_date
      errors.add(:birthday, 'The patient should be over 12 years old.')
    elsif birthday.present? && birthday < 21.years.ago.to_date
      errors.add(:birthday, 'The patient should be less than 21 years old.')
    end
  end

  def height_in_feet
    return I18n.t('common.values.n_a') unless height
    feet = height / 12
    inches = height % 12
    "#{feet}\' #{inches}\""
  end

  def weight_in_pounds
    return I18n.t('common.values.n_a') unless weight
    "#{weight.round(2)} lbs"
  end

  def read_notifications
    read_control_notification_records.map(&:control_notification)
  end

  def unread_notifications
    control_notifications.where.not(id: read_notifications.pluck(:id))
  end
end

peakasthma-web/app/controllers/control_patients_controller.rb
require 'will_paginate/array'

class ControlPatientsController < ApplicationController
  authenticated!
  before_action :redirect_wrong_patient
  before_action :find_patient, only: [:show, :edit, :update]

  def index
    if params[:search].blank?
      @controlPatients = ControlPatient.all.order(updated_at: :desc).paginate(page: params[:page])
    else
      @parameter = params[:search].downcase
      @controlPatients = ControlPatient.joins(:user).where("lower(CONCAT(users.first_name, ' ', users.last_name)) LIKE :search", search: "%#{@parameter}%").order(updated_at: :desc).paginate(page: params[:page])
    end
    
  end

  def update
    @controlPatient.update(patient_params)
    respond_with @controlPatient
  end

  def show
    # @week_incentives = ControlIncentiveRecord.where(control_patient_id: params[:id], month: month, week: week, get_incentive: true)
    # @total_incentives = ControlIncentiveRecord.where(control_patient_id: params[:id], get_incentive: true)
    @diet_records = DietRecord.where("control_patient_id = ?", @controlPatient.id).order(record_date: :desc).paginate(page: params[:diet_records_page], per_page: 6)
    
    @days = days_after_enroll()
    @months = @days / 30 + 1
    @monthly_rewards_days = Hash.new
    for i in (1..@months)
      @monthly_rewards_days[i] = 0
    end
    
    @all_incentives = ControlIncentiveRecord.where(control_patient_id: params[:id]).order(month: :asc, week: :asc, day: :asc)
    @all_incentives = @all_incentives.to_a
    @all_incentives.each_with_index do |incentive, index|
      total_days = (incentive.week - 1) * 7 + incentive.day
      true_month = (total_days - 1) / 30 + 1
      if @monthly_rewards_days.include?(true_month) and @monthly_rewards_days[true_month] >= 20
        @all_incentives[index].get_incentive = false
      else
        @all_incentives[index].get_incentive = true
        @monthly_rewards_days[true_month] += 1
      end 
      @all_incentives[index]['month'] = true_month
      @all_incentives[index]['day'] = total_days - 30 * (true_month-1)
    end
    @incentives =  @all_incentives.paginate(page: params[:incentives_page], per_page: 5)
    @len = @monthly_rewards_days.length - 1
    if @len >= 0
      @month_incentives = @monthly_rewards_days.values[@len]
      last_month = @monthly_rewards_days.keys[@len]
      @monthly_rewards_days.delete(last_month)
    else
      @month_incentives = 0
      last_month = 0
    end
    @total_incentives = @all_incentives.select do |elem|
      elem.get_incentive == true
    end

  end

  def edit
    fill_redcap_data(@controlPatient, params['import-redcap-id'])
  end

  def new
    @controlPatient = ControlPatient.new
    @controlPatient.user = User.new
    fill_redcap_data(@controlPatient, params['import-redcap-id'])
  end

  def create
    @controlPatient = ControlPatient.create(patient_params)
    respond_with @controlPatient
  end

  private
    def patient_params
      valid_params = params.require(:control_patient).permit(
        :daily_reminders,
        :daily_reminder_time,
        :gender,
        :birthday,
        :height,
        :weight,
        :phone, 
        :physician,
        :redcap_id,
        user_attributes: [:id, :first_name, :last_name, :username, :email, :role, :disabled])
  
        if valid_params[:daily_reminder_time]
          valid_params[:daily_reminder_time] = valid_params[:daily_reminder_time].to_time
        end

        valid_params[:user_attributes][:encrypted_password] = '$2a$11$cixW0odcieVc4XgCQ.mu.evLbsvuR/6aqANX/8Sup8EXPU/gkDNP6' if action_name == 'create'

        valid_params
    end

    def find_patient
      @controlPatient = ControlPatient.find(params[:id])
      @controlPatient
    end

    def days_after_enroll()
      @enroll_date = @controlPatient.created_at.to_date
      @current_date = Time.now.utc.to_date
      @days = @current_date - @enroll_date
      @days = @days.to_i
    end

    def day
        @days = days_after_enroll()
        @week_day = (@days % 7) + 1
    end

    def week
        @days = days_after_enroll()
        @week = (@days / 7) + 1
    end

    def month
        @month = ((week - 1) / 4) + 1 
    end

    def fill_redcap_data(control_patient, redcap_id)
      info = RedcapAPI.get_patient_demographic_info(redcap_id)

      control_patient.birthday = info[:dob] if info[:dob] != nil
      control_patient.gender = info[:gender] if info[:gender] != nil
      control_patient.physician = info[:pcp] if info[:pcp] != nil
      control_patient.height = info[:height] if info[:height] != nil
      control_patient.weight = info[:weight] if info[:weight] != nil
      control_patient.redcap_id = redcap_id if redcap_id != nil

      control_patient.user.first_name = info[:first_name] if info[:first_name] != nil
      control_patient.user.last_name = info[:last_name] if info[:last_name] != nil
    end
end

peakasthma-web/app/views/control_patients/_diet_table.html.erb
<div class="peak-flow-table">
  <table class="table" id="patient-index-table">
    <thead>
      <tr>
        <th>
          <%= t('diet.created_date') %>
        </th>
        <th>
          <%= t('diet.fruit') %>
        </th>
        <th>
          <%= t('diet.vegetable') %>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @diet_records.each do |record| %>
        <tr>
          <td>
            <%= record.record_date %>
          </td>
          <td>
            <%= record.fruit %> servings
          </td>
          <td>
            <%= record.vegetable %> servings
          </td>
        </tr>
      <% end %>
    </tbody>
    </table>
    <div class="digg_pagination">
    <%= will_paginate @diet_records, :param_name => 'diet_records_page' %>
    </div>
</div>

peakasthma-web/app/views/control_patients/_form.html.erb
<div class="row">
  <div class="col-xs-12">
    <% if controller.action_name == "new" || controller.action_name == "create" %>
      <%= form_tag(new_control_patient_url, method: "get") do %>
        <%= label_tag("import-redcap-id", "REDCap ID:") %>
        <%= text_field_tag("import-redcap-id") %>
        <%= submit_tag("Import Demographic Information from REDCap", class: "btn btn-info back-btn") %>
      <% end %>
    <% elsif controller.action_name == "edit" || controller.action_name == "update" %>
      <%= form_tag(edit_control_patient_url(params[:id]), method: "get") do %>
        <%= label_tag("import-redcap-id", "REDCap ID:") %>
        <%= text_field_tag("import-redcap-id") %>
        <%= submit_tag("Import Demographic Information from REDCap", class: "btn btn-info back-btn") %>
      <% end %>
    <% end %>
  </div>
</div>
<%= simple_form_for @controlPatient do |patient| %>
  <% patient.simple_fields_for :user do |user| %>
    <%= user.input :id, as: :hidden %>
    <div class="row">
      <div class="col-xs-12">
        <div class="panel panel-default">
          <div class="panel-body">
            <h2>
              <%= t('control_patient.views.headers.personal_information') %>
            </h2>
              <div class="row">
                <div class="col-xs-6">
                  <%= user.input :first_name %>
                </div>
                <div class="col-xs-6">
                  <%= user.input :last_name %>
                </div>
              </div>
            <div class="row">
              <div class="col-xs-4 col-md-3">
                <%= patient.input :gender, collection: ControlPatient::GENDERS %>
              </div>
              <div class="col-xs-8 col-md-3">
                <%= patient.input :birthday, html5: true%>
              </div>
              <div class="col-xs-6 col-md-3">
                <%= patient.input :weight %>
              </div>
              <div class="col-xs-6 col-md-3">
                <%= patient.input :height,  input_html: { min: '0', max: '90', value: patient.object.height || '0' } %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <div class="panel panel-default">
          <div class="panel-body">
            <h2>
              <%= t('control_patient.views.headers.additional_info') %>
            </h2>
            <div class="row">
              <div class="col-xs-12 col-md-8">
                <%= user.input :username %>
                <%= user.input :email %>
                <%= user.input :role, as: :hidden, html5: true, input_html: { value: :control_patient } %>
              </div>
              <div class="col-xs-12 col-md-4">
                <%= patient.input :phone, placeholder: "123-456-7890" %>
                <%= patient.input :physician %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-4">
        <div class="panel panel-default">
          <div class="panel-body">
            <h2>
              <%= t('control_patient.views.headers.daily_reminders') %>
            </h2>
            <%= patient.input :daily_reminders, as: :hidden, wrapper: :checkbox, :input_html => { :value => 1 } %>
            <%= patient.input :daily_reminder_time, as: :hidden, html5: true %>
            <%= patient.simple_fields_for :time do |nf| %>
              <%= nf.input :daily_reminder_time, as: :time, html5: true %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-md-4">
        <div class="panel panel-default">
          <div class="panel-body">
            <h2>
              <%= t('control_patient.views.headers.redcap_id') %>
            </h2>
            <%= patient.input :redcap_id, label: 'Record ID' %>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-md-4">
        <div class="panel panel-default">
          <div class="panel-body">
            <h2>
              <%= t('user.views.headers.account_status') %>
            </h2>
            <%= user.input :disabled, as: :select, label: 'Mobile App Usage', collection: [['Active', false], ['Disabled', true]], include_blank: false %>
          </div>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-body">
        <%= patient.button :submit, class: 'btn-default' %>
      </div>
    </div>
  <% end %>
<% end %>

peakasthma-web/app/views/control_patients/_patient_additional_info_table.html.erb
<div class="patient-profile__table-header">
  <%= t('patient.views.headers.additional_info') %>
</div>
<div class="panel panel-default">
  <div class="patient-profile-table">
    <%= render 'shared/mobile_table_row', block_name: 'patient-profile-table', header: t('user.model.email'), value: @controlPatient.user.email %>
    <%= render 'shared/mobile_table_row', block_name: 'patient-profile-table', header: t('user.model.username'), value: @controlPatient.user.username %>
    <%= render 'shared/mobile_table_row', block_name: 'patient-profile-table', header: t('user.model.phone'), value: @controlPatient.phone %>
    <%= render 'shared/mobile_table_row', block_name: 'patient-profile-table', header: t('control_patient.model.physician'), value: @controlPatient.physician %>
    <%= render 'shared/mobile_table_row', block_name: 'patient-profile-table', header: t('control_patient.model.start_date'), value: l(@controlPatient.created_at) %>
    <%= render 'shared/mobile_table_row', block_name: 'patient-profile-table', header: t('control_patient.model.redcap_id'), value: @controlPatient.redcap_id %>
    <%= render 'shared/mobile_table_row', block_name: 'patient-profile-table', header: t('user.model.account_status'), value: @controlPatient.user.disabled ? 'Disabled' : 'Active' %>
  </div>
</div>

peakasthma-web/app/views/control_patients/_patient_info_table.html.erb
<div class="panel panel-default highlighted">
  <div class="patient-profile-table highlighted">
    <%= render 'shared/mobile_table_row', block_name: 'patient-profile-table', header: t('control_patient.model.full_name'), value: @controlPatient.full_name %>
    <%= render 'shared/mobile_table_row', block_name: 'patient-profile-table', header: t('control_patient.model.birthday'), value: @controlPatient.birthday %>
    <%= render 'shared/mobile_table_row', block_name: 'patient-profile-table', header: t('control_patient.model.height_in_feet'), value: @controlPatient.height_in_feet %>
    <%= render 'shared/mobile_table_row', block_name: 'patient-profile-table', header: t('control_patient.model.weight_in_pounds'), value: @controlPatient.weight_in_pounds %>
    <%= render 'shared/mobile_table_row', block_name: 'patient-profile-table', header: t('control_patient.model.gender'), value: t("#{@controlPatient.gender}") %>
  </div>
</div>

peakasthma-web/app/views/control_patients/_patient_table.html.erb
<table class="table" id="patient-index-table">
  <thead>
    <tr>
      <th>
        <%= t('patient.model.full_name') %>
      </th>
      <th>
        <%= t('patient.model.height') %>
      </th>
      <th>
        <%= t('patient.model.weight') %>
      </th>
      <th>
        <%= t('patient.model.gender') %>
      </th>
      <!-- <th>
        <%= t('patient.model.race') %>
      </th>
      <th>
        <%= t('patient.model.zip_code') %>
      </th> -->
      <th>
        <%= t('patient.model.updated_at') %>
      </th>
      <th>
        <%= t('user.model.account_status') %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @controlPatients.each do |patient| %>
      <tr>
        <td>
          <%= link_to patient.full_name, control_patient_url(patient) %>
        </td>
        <td>
          <%= patient.height_in_feet %>
        </td>
        <td>
          <%= patient.weight_in_pounds %>
        </td>
        <td>
          <%= patient.gender %>
        </td>
        <!-- <td>
          <%= patient.race %>
        </td> -->
        <td>
          <%= l patient.updated_at %>
        </td>
        <td>
          <%= patient.user.disabled ? 'Disabled' : 'Active' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

peakasthma-web/app/views/control_patients/edit.html.erb
<%= render 'form' %>

peakasthma-web/app/views/control_patients/index.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-8">
    <div class="panel panel-default">
      <div class="panel-body text-center">
        <%= link_to t('control_patient.views.buttons.create'), new_control_patient_path, class: 'btn btn-success' %>
      </div>
    </div>
  </div>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="text-center">
                <%= form_tag(control_patients_url, method: "get", class: "flex-row") do %>
                  <%= search_field_tag :search, params[:search], placeholder: "Control Patient Name", class: "form-control" %>
                  <div class="input-group-btn">
                      <%= button_tag "Search", :class => 'btn btn-info', :name => nil %>
                  </div>
                <% end %>
            </div>
        </div>
    </div>
</div>
<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'patient_table' %>
    <%= will_paginate @controlPatients %>
  </div>
</div>

peakasthma-web/app/views/control_patients/new.html.erb
<%= render 'form' %>

peakasthma-web/app/views/control_patients/show.html.erb
<div class="patient-profile">
  <div class="row">
    <div class="col-lg-3 col-md-4">
      <% if current_user&.admin? %>
        <%= link_to new_control_patient_control_notification_path(@controlPatient), class: 'btn btn-success btn-block' do %>
          <span class="glyphicon glyphicon-envelope"></span>
          Send Message
        <% end %>
      <% end %>
      <br>
      <% if current_user&.admin? %>
        <%= link_to edit_control_patient_path(@controlPatient), class: 'btn btn-info btn-block' do %>
          <span class="glyphicon glyphicon-edit"></span>
          <%= t('patient.views.buttons.edit') %>
        <% end %>
      <% end %>
      <br>
      <%= render partial: 'control_patients/patient_info_table' %>
      <%= render partial: 'control_patients/patient_additional_info_table' %>
      <% if current_user&.admin? %>
        <%= render partial: 'control_incentive/rewards_table' %>
      <% end %>
    </div>

    <div class="col-lg-9 col-md-8">
      <% if current_user&.admin? %>
        <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-default">
              <div class="recent-peak-flows__header">
                <%= t('dashboard.headers.incentive') %>
              </div>
              <%= render 'control_incentive/incentives_table' %>
            </div>
          </div>
        </div>
      <% end %>

      <% if current_user&.admin? %>
        <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-default">
              <div class="recent-peak-flows__header">
                <%= t('dashboard.headers.monthly_reward') %>
              </div>
              <%= render 'incentive/monthly_reward_table' %>
            </div>
          </div>
        </div>
      <% end %>

      <div class="row">
        <div class="col-lg-12">
          <div class="panel panel-default">
            <div class="recent-peak-flows__header">
              <%= t('diet.record') %>
            </div>
            <%= render 'control_patients/diet_table' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>