peakasthma-web/config/routes.rb
Rails.application.routes.draw do

  get 'twilio_messages/reply'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  mount Avocado::Engine => '/avocado'

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
                     :controllers => {:confirmations => 'confirmations'}
  devise_scope :user do
    put "/confirm" => "confirmations#confirm"
  end

  namespace :api, defaults: { format: :json } do
    devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' }

    get 'users/current', to: 'users#current'
    post 'users/accept_policy', to: 'users#accept_policy'
    get 'tip', to: 'tips#get_tip'
    post 'weather', to: 'tips#get_weather'
    post 'video', to: 'videos#likeVideo'
    get 'video', to: 'videos#avbVideo'
    get 'medicationreminder/:minutes/:color', to: 'taken_prescription_records#reminder_later'
    get 'incentive', to: 'incentive#incentive'
    get 'survey', to: 'survey#survey'
    post 'clincard_balance_request', to: 'clincard_balance_requests#send_request'
    resources :activities, only: [:index]
    resources :peak_flows, only: [:create, :index]
    resources :prescriptions, only: [:index] do
      post :notifications, on: :collection
      post :reports, on: :collection
      post :remindmelater, on: :collection
    end
    resources :symptoms, only: [:index]
    resources :read_notification_records, only: [:create]
    resources :taken_prescription_records, only: [:create]
    resources :notifications, only: [:index]

    namespace :control, defaults: { format: :json } do
      get 'users/current', to: 'users#current'
      post 'users/accept_policy', to: 'users#accept_policy'
      resources :activities, only: [:index]
      resources :diet_records, only: [:create, :index, :update]
      resources :notifications, only: [:index]
      post 'daily_reminder', to: 'notifications#daily_reminder'
      resources :read_notification_records, only: [:create]
      get 'incentive', to: 'incentive#incentive'
      get 'control_survey', to: 'control_survey#survey'
      post 'clincard_balance_request', to: 'clincard_balance_requests#send_request'
    end
  end
  
  resources :users do
    post :create_admin, on: :collection
  end

  resource :twilio_notifications do
    collection do
      post 'reply'
    end
  end
  post 'red_voice', to: 'twilio_notifications#red_voice', defaults: { format: 'xml' }
  post 'yellow_voice', to: 'twilio_notifications#yellow_voice', defaults: { format: 'xml' }
  get 'tip/:id', to: 'tips#send_tip'
  resources :medications
  resources :symptoms
  resources :tips
  resources :videos
  resources :exacerbations
  resources :patient_reward_records
  resources :control_patient_reward_records
  resources :patient_visits_records
  resources :control_patient_visits_records
  resources :clincard_balance_requests
  resources :alert_tables
  resources :patients, only: [:index, :show, :edit, :update, :new, :create] do
    resources :peak_flows, only: [:index]
    resources :prescriptions do
      get :fields, on: :collection
      resources :prescription_refill_records
    end
    resources :prescriptions
    resources :notifications do
      get :fields, on: :collection
    end
    resources :guardians
    resources :reports, only: [:show]
  end
  resources :notifications, only: [:index, :create, :edit, :update, :new, :destroy] do
    get :fields, on: :collection
  end

  resources :control_patients, only: [:index, :show, :edit, :update, :new, :create] do
    resources :control_notifications
  end
  resources :control_notifications, only: [:index, :create, :edit, :update, :new, :destroy]
  root to: 'dashboard#root'
end

peakasthma-web/app/models/video.rb
class Video < ApplicationRecord
    has_and_belongs_to_many :patients

    validates :video_name, presence: true
    validates :url, presence: true
    validates :week, presence: true
    validates :day, presence: true
end

peakasthma-web/app/controllers/api/videos_controller.rb
module API
  class VideosController < API::BaseController
    authenticated!
    before_action :find_video, only: [:likeVideo] 
    
    def avbVideo
      @videos = Video.all.order(week: :asc, day: :asc)
      @like_videos = current_user.patient.videos
      respond_with [@videos, @like_videos]
    end
    
    def likeVideo
      LikeVideoJob.perform_later(current_user.patient, @video)
    end

    private
      def find_video
        @video = Video.find(params[:video_id])
      end
  end
end

peakasthma-web/app/controllers/videos_controller.rb
class VideosController < ApplicationController
    authenticated!

    before_action :redirect_non_admin
    before_action :find_video, only: [:edit, :update, :destroy, :show]

    def index
        @videos = Video.all.order([:week, :day]).paginate(page: params[:page])
    end

    def create
        @video = Video.create(video_params)
        respond_with @video, location: videos_path
    end

    def update
        @video.update(video_params)
        respond_with @video, location: videos_path
    end

    def destroy
        @video.destroy
        respond_with @video, location: videos_path
    end

    def edit
    end

    def show
    end

    def new
        @video = Video.new
    end

    private
        def find_video
            @video = Video.find(params[:id])
        end

        def video_params
            params.require(:video).permit(:video_name, :url, :week, :day)
        end
end

peakasthma-web/app/views/videos/_form.html.erb
<%= simple_form_for video do |f| %>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :video_name %>
      <%= f.input :url %>
      <%= f.input :week %>
      <%= f.input :day %>
    </div>
  </div>
  <%= f.button :submit, class: 'btn-default' %>
<% end %>

peakasthma-web/app/views/videos/_video.html.erb
<tr id="<%= "video-#{video.id}" %>">
  <td>
    <%= link_to video.video_name, edit_video_url(video) %>
  </td>
  <td>
    <%= link_to video.url, "https://app.vidscrip.com/vidscrip/#{video.url}?qs=1&q=1", target: :_blank %>
  </td>
  <td>
    <%= t(video.week) %>
  </td>
  <td>
    <%= t(video.day) %>
  </td>
  <td>
    <%= video.patients.length %>
  </td>
  <td>
    <%= link_to video, method: :delete, remote: true, data: {confirm: t('video.views.delete_confirm')}, id: "#{video.id}_delete" do%>
      <span class="glyphicon glyphicon-remove pull-right text-danger"></span>
    <% end %>
  </td>
</tr>

peakasthma-web/app/views/videos/edit.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'form', video: @video %>
  </div>
</div>

peakasthma-web/app/views/videos/index.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-8">
    <div class="panel panel-default">
      <div class="panel-body text-center">
        <%= link_to t('video.views.buttons.create'), new_video_path, class: 'btn btn-success' %>
      </div>
    </div>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-body">
    <table class="table" id="symptoms-index-table">
      <thead>
        <tr>
          <th>
            Video Name
          </th>
          <th>
            Url
          </th>
          <th>
            Week
          </th>
          <th>
            Day
          </th>
          <th>
            Like
          </th>
        </tr>
      </thead>
      <tbody>
        <%= render @videos %>
      </tbody>
    </table>
    <%= will_paginate @videos %>
  </div>
</div>

peakasthma-web/app/views/videos/new.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'form', video: @video %>
  </div>
</div>