peakasthma-web/config/routes.rb
Rails.application.routes.draw do

  get 'twilio_messages/reply'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  mount Avocado::Engine => '/avocado'

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
                     :controllers => {:confirmations => 'confirmations'}
  devise_scope :user do
    put "/confirm" => "confirmations#confirm"
  end

  namespace :api, defaults: { format: :json } do
    devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' }

    get 'users/current', to: 'users#current'
    post 'users/accept_policy', to: 'users#accept_policy'
    get 'tip', to: 'tips#get_tip'
    post 'weather', to: 'tips#get_weather'
    post 'video', to: 'videos#likeVideo'
    get 'video', to: 'videos#avbVideo'
    get 'medicationreminder/:minutes/:color', to: 'taken_prescription_records#reminder_later'
    get 'incentive', to: 'incentive#incentive'
    get 'survey', to: 'survey#survey'
    post 'clincard_balance_request', to: 'clincard_balance_requests#send_request'
    resources :activities, only: [:index]
    resources :peak_flows, only: [:create, :index]
    resources :prescriptions, only: [:index] do
      post :notifications, on: :collection
      post :reports, on: :collection
      post :remindmelater, on: :collection
    end
    resources :symptoms, only: [:index]
    resources :read_notification_records, only: [:create]
    resources :taken_prescription_records, only: [:create]
    resources :notifications, only: [:index]

    namespace :control, defaults: { format: :json } do
      get 'users/current', to: 'users#current'
      post 'users/accept_policy', to: 'users#accept_policy'
      resources :activities, only: [:index]
      resources :diet_records, only: [:create, :index, :update]
      resources :notifications, only: [:index]
      post 'daily_reminder', to: 'notifications#daily_reminder'
      resources :read_notification_records, only: [:create]
      get 'incentive', to: 'incentive#incentive'
      get 'control_survey', to: 'control_survey#survey'
      post 'clincard_balance_request', to: 'clincard_balance_requests#send_request'
    end
  end
  
  resources :users do
    post :create_admin, on: :collection
  end

  resource :twilio_notifications do
    collection do
      post 'reply'
    end
  end
  post 'red_voice', to: 'twilio_notifications#red_voice', defaults: { format: 'xml' }
  post 'yellow_voice', to: 'twilio_notifications#yellow_voice', defaults: { format: 'xml' }
  get 'tip/:id', to: 'tips#send_tip'
  resources :medications
  resources :symptoms
  resources :tips
  resources :videos
  resources :exacerbations
  resources :patient_reward_records
  resources :control_patient_reward_records
  resources :patient_visits_records
  resources :control_patient_visits_records
  resources :clincard_balance_requests
  resources :alert_tables
  resources :patients, only: [:index, :show, :edit, :update, :new, :create] do
    resources :peak_flows, only: [:index]
    resources :prescriptions do
      get :fields, on: :collection
      resources :prescription_refill_records
    end
    resources :prescriptions
    resources :notifications do
      get :fields, on: :collection
    end
    resources :guardians
    resources :reports, only: [:show]
  end
  resources :notifications, only: [:index, :create, :edit, :update, :new, :destroy] do
    get :fields, on: :collection
  end

  resources :control_patients, only: [:index, :show, :edit, :update, :new, :create] do
    resources :control_notifications
  end
  resources :control_notifications, only: [:index, :create, :edit, :update, :new, :destroy]
  root to: 'dashboard#root'
end

peakasthma-web/app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  authenticated!
  before_action :redirect_wrong_patient
  before_action :find_patient, only: [:show]

  def show
    enroll_date = Date.parse(@patient.created_at.to_s)
    @start_date = enroll_date + (Integer(params[:id]) - 1) * 30
    @end_date = (enroll_date + Integer(params[:id]) * 30) - 1

    @green_count = 0
    @yellow_count = 0
    @red_count = 0

    peak_flows = @patient.peak_flows.where(created_at: (@start_date..@end_date)).order("created_at asc")
    filtered = []
    current_date = Date.parse(peak_flows[0].created_at.to_s) if !peak_flows.empty?
    current_level = peak_flows[0].level() if !peak_flows.empty?
    for p in peak_flows
      level = p.level()
      if current_date === Date.parse(p.created_at.to_s)
        if compare(current_level, level) == -1
          current_level = level
        end
      else
        filtered << { date: current_date, level: current_level }
        current_date = Date.parse(p.created_at.to_s)
        current_level = level
      end
    end
    filtered << { date: current_date, level: current_level } if !peak_flows.empty?

    for r in filtered
      if r[:level] == :green
        @green_count += 1
      elsif r[:level] == :yellow
        @yellow_count += 1
      else
        @red_count += 1
      end
    end

    month = Integer(params[:id])
    data = RedcapAPI.get_patient_monthly_survey(@patient.redcap_id, month)

    if data != nil
      if month == 6 || month == 9
        @emt = Integer(data[0]['m69_er'])
        @hospital = Integer(data[0]['m69_overnight'])
        @doctor = Integer(data[0]['m69_dr'])
        @rescue = Integer(data[0]['m69_rescue'])
      else
        @emt = Integer(data[0]['m_er'])
        @hospital = Integer(data[0]['m_overnight'])
        @doctor = Integer(data[0]['m_dr'])
        @rescue = Integer(data[0]['m_rescue'])
      end
    else
      @emt = 0
      @hospital = 0
      @doctor = 0
      @rescue = 0
    end
  end

  private
    def find_patient
      @patient = Patient.find(params[:patient_id])
    end

    def compare(l, r)
      l_index = PeakFlow::LEVELS.find_index(l)
      r_index = PeakFlow::LEVELS.find_index(r)
      l_index <=> r_index
    end
end

peakasthma-web/app/views/reports/_report_table.html.erb
<div class="peak-flow-table">
  <table class="table">
    <thead>
      <tr>
        <th class="peak-flow-table__level">
          <%= t('patient.views.reports.create_at') %>
        </th>
        <th>
          <%= t('patient.views.reports.action.action') %>
        </th>
        <th></th>
      </tr>
    </thead>
    <% if reports&.any? %>
      <tbody>
        <% reports.each do |report| %>
          <tr>
            <td class="peak-flow-table__level">
              <%= l(report[:start]) + ' - ' + l(report[:end]) %>
            </td>
            <td>
              <%= link_to patient_report_path(@patient, report[:report_id]) do %>
                <button class="btn btn-primary btn-xs">
                  <%= t('patient.views.reports.action.view') %>
                </button>
              <% end %> 
            </td>
          </tr>
        <% end %>
      </tbody>
    <% end %>
  </table>
  <% if !reports || reports.empty? %>
    <div class="peak-flow-table__no-peak-flows">
      <%= t('patient.views.reports.no_values') %>
    </div>
  <% end %>
</div>

peakasthma-web/app/views/reports/show.html.erb
<script>
  var reportPeriod = "<%= "#{@start_date.to_s().gsub('-', '/')} - #{@end_date.to_s().gsub('-', '/')}" %>";
  var filename = "<%= "#{@patient.user.first_name}#{@patient.user.last_name}_#{@start_date.to_s().delete('-')}-#{@end_date.to_s().delete('-')}" %>";
  var green_count = <%= @green_count %>;
  var yellow_count = <%= @yellow_count %>;
  var red_count = <%= @red_count %>;
</script>

<%= link_to patient_url(@patient) do %>
  <button class="btn btn-danger back-btn">
    Go Back
  </button>
<% end %>

<button class="btn btn-danger back-btn" onclick="downloadPDF();">
  Download PDF
</button>

<div class="report" id="reportPDF">
  <div class="panel panel-default">
    <div class="panel-body">
      <header class="report__header">
        <h1>
          <%= "Monthly Asthma Report" %>
        </h1>
        <h2>
          <%= "Patient Name: #{@patient.user.first_name} #{@patient.user.last_name}" %>
        </h2>
        <h2>
          <%= "Report Time Period: #{@start_date.to_s().gsub('-', '/')} - #{@end_date.to_s().gsub('-', '/')}" %>
        </h2>
      </header>
      <div class="report__graph-container">
        <canvas id="reportChart" width="100mm" height="80mm"></canvas>
        <script>renderReportChart();</script>
      </div>
      <div calss="report__tables-container">
        <div class="col-md-8">
          <table class="table">
            <thead>
              <tr>
                <th>HEALTHCARE &nbsp; UTILIZATION</th>
                <th># of VISITS</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>ED</td>
                <td>
                  <%= @emt %>
                </td>
              </tr>
              <tr>
                <td>Hospitalizations</td>
                <td>
                  <%= @hospital %>
                </td>
              </tr>
              <tr>
                <td>Acute Healthcare</td>
                <td>
                  <%= @doctor %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="col-md-4">
          <table class="table">
            <thead>
              <tr>
                <th># of DAYS RESCUE MEDICATION &nbsp;USED</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <%= @rescue %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>